---
- name: Yum
  block:
    - name: Add MariaDB Repo
      yum_repository:
        name: MariaDB
        description: MariaDB YUM Repo
        baseurl: "http://yum.mariadb.org/{{ mariadb_version }}/centos7-amd64"
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: yes
        enabled: yes
      when: ansible_distribution == 'CentOS'

    - name: Add MariaDB Repo
      yum_repository:
        name: MariaDB
        description: MariaDB YUM Repo
        baseurl: "http://yum.mariadb.org/{{ mariadb_version }}/rhel7-amd64"
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: yes
        enabled: yes
      when: ansible_distribution == 'Red Hat Enterprise Linux'
    
    - name: Install Software
      yum: 
        name: "{{ packages }}"
        update_cache: yes
  tags: t_yum